load("//bazel:defs.bzl", "walgit_rust_crate")

walgit_rust_crate(
    name = "walgit-cli",
    crate_name = "walgit_cli",
    binary_deps = ["@walgit_crates//:anyhow"],
    binaries = {
        "walgit": "src/bin/walgit.rs",
        "walgit-server": "src/bin/walgit-server.rs",
    },
    deps = [
        "//crates/walgit-config",
        "//crates/walgit-git",
        "//crates/walgit-proto",
        "//crates/walgit-server",
        "//crates/walgit-store",
        "//crates/walgit-wal",
        "@walgit_crates//:anyhow",
        "@walgit_crates//:axum",
        "@walgit_crates//:bytes",
        "@walgit_crates//:chrono",
        "@walgit_crates//:clap",
        "@walgit_crates//:futures",
        "@walgit_crates//:gix-hash",
        "@walgit_crates//:hex",
        "@walgit_crates//:humantime",
        "@walgit_crates//:mimalloc",
        "@walgit_crates//:parking_lot",
        "@walgit_crates//:rand",
        "@walgit_crates//:reqwest",
        "@walgit_crates//:rustls",
        "@walgit_crates//:serde",
        "@walgit_crates//:serde_json",
        "@walgit_crates//:sha1",
        "@walgit_crates//:tempfile",
        "@walgit_crates//:tokio",
        "@walgit_crates//:tokio-util",
        "@walgit_crates//:toml",
        "@walgit_crates//:tracing",
        "@walgit_crates//:tracing-subscriber",
    ],
)
